### ISSUE TITLE
How to add Linux entry to Clover screen?

### ISSUE THREAD

**Issue by Jinzhengxu** [zhtengw/EFI-for-X1C6-hackintosh#1]
I have thinkpad x1 carbon which already installed ubuntu18.04 and win10. When I replaced EFI with those file, I only get win and macOS in Clover. If I want to use ubuntu that must press F12 to get to Boot menu. So how to deal with that?

**Comment by zhtengw** [comment]
Put VBoxExt2.efi and VBoxExt4.efi into your /EFI/CLOVER/drivers/UEFI/, and have a try.


[VBoxExt2:4.zip](https://github.com/zhtengw/EFI-for-X1C6-hackintosh/files/3821107/VBoxExt2.4.zip)

**Comment by Jinzhengxu** [comment]
I try this
```
$ mount /dev/nvme0n1p1 /mnt/home
$ cp VBoxExt* /mnt/home/EFI/CLOVER/drivers/UEFI/
$ ls 
ApfsDriverLoader.efi  OsxAptioFix3Drv.efi  VBoxExt4.efi
HFSPlus.efi           VBoxExt2.efi         VirtualSmc.efi
```
and reboot, but it still only have win, macos and macOS  Recovery on Clover start screen.

**Comment by zhtengw** [comment]
I check the config.plist, and found that "GUI-->Scan-->Linux" was configured to "false".
https://github.com/zhtengw/EFI-for-X1C6-hackintosh/blob/0a4e653577bb021939a7be10f0acd4642252fa34/Clover/EFI/CLOVER/config.plist#L322-L323
Change it to "true" may help you.

**Comment by Jinzhengxu** [comment]
Now it work🎉, Thanks for your answer!😃
