### ISSUE TITLE
Doubt about SM961

### ISSUE THREAD

**Issue by zombillano** [zhtengw/EFI-for-X1C6-hackintosh#13]
Hi there! I have a problem with SM961 and I would like to ask you if you can reproduce it. I'm using opencore and I'm getting an strange behavour with the SSD, I get full speed benchmarks (~1400MB/s Read / ~1300MB/s Write) but I'm getting a sustancial slow down (~400MB/s on both Read and Write) after waking up from sleep. I tried with and without NVMeFix kext but I'm still getting the same behavour. I must say that I'm having this problem on a T480 so it has nothing to do with your OpenCore config files, but I am trying to see if this is a general behavour and if not then I'll try to see what's the difference between your OpenCore config and mine when talking about SSD. Hope you can help me. Thanks in advance!

Note: I'm using macOS 10.15.5 if that changes anything.

**Comment by zhtengw** [comment]
I just install the `black Disk Speed Test` from App Store and have a benchmark test. Get ~1800MB/s Read and ~1200MB/s Write before sleep and after waking up. I did not do any special for the SSD expect the NVMeFix.kext. And I have no idea on resolving your issue.
![截屏2020-06-25 08 53 08](https://user-images.githubusercontent.com/3148769/85641539-710f6880-b6c1-11ea-9ab9-3f2fd9dfe861.png)

And my personal suggestion is, if the disk speed does not obstruct you from working, never mind the benchmarks.

**Comment by zombillano** [comment]
It does because I happen to have multiple VM's working and it starts to get slower after sleep. I will try to find the differences related to SSD between your OpenCore config and mine. Thanks for taking the time to reply!
