### ISSUE TITLE
触摸板有时候启动不好使

### ISSUE THREAD

**Issue by z-x-f** [zhtengw/EFI-for-X1C6-hackintosh#5]
一般冷启动后可以正常启动，有时候重启或者从windows重启到osx的时候触摸板就变成一指无反应，二指变成移动鼠标指针了

**Comment by zhtengw** [comment]
是的，VoodooPS2更新2.1之后会有这个问题，如果觉得困扰，建议使用旧版的VoodooPS2Controller 2.0.3，并删除VoodooInput。

**Comment by z-x-f** [comment]
新版起码二指三指好用点，不过平时还是小红点居多，先这样吧，看看以后会不会修复
