### ISSUE TITLE
How did you manage to place BCM94360CS2 + adapter inside a case?

### ISSUE THREAD

**Issue by igavrysh** [zhtengw/EFI-for-X1C6-hackintosh#6]
I bought BCM94360CS2 + NGIFF M2 adapter:
![s-l1600 (1)](https://user-images.githubusercontent.com/10332978/77830675-59870a80-70e7-11ea-9085-a696326359ae.jpg)

However, when I tried to put everything inside my Thinkpad X1 Gen 6, the laptop back cover was not able to close due to height of adapter + card. +there is no space inside for adapter and as a result, it partially covers SSD drive. No way I can close back cover without damaging it.

How did you cope with those problems?

Thanks!

**Comment by zhtengw** [comment]
Hi, I just cut the adapter shorter(see the red line in the picture below). 

![77830675-59870a80-70e7-11ea-9085-a696326359ae](https://user-images.githubusercontent.com/3148769/77833914-c6e47b00-717b-11ea-9b54-98327a57b7b6.png)

**Comment by igavrysh** [comment]
Thx a lot, it worked!

**Comment by dragoncode** [comment]
May I ask what you used to cut it? What is the best way to avoid causing damage? Thanks a lot in advance.
