### ISSUE TITLE
可以分享下蓝牙驱动文件吗？

### ISSUE THREAD

**Issue by johnzhaoican** [zhtengw/EFI-for-X1C6-hackintosh#7]
您好，我的机型也是20KG*，我在淘宝上买了DW1560网卡，请问可以分享下DW1560的蓝牙补丁文件吗？
例如：
BrcmBluetoothInjector. Kext
BrcmFirmwareData.kext
BrcmPatchRAM3.kext
AirportBrcmFixup.kext
AirportBrcmFixup.kext
非常感谢！

**Comment by z-x-f** [comment]
bcm94360cs2直接免驱的，所以你找错地方了呃

**Comment by johnzhaoican** [comment]
> bcm94360cs2直接免驱的，所以你找错地方了呃

你好朋友，这个在15.04上是不免驱的。关于这个问题我已经在：
https://github.com/tylernguyen/x1c6-hackintosh/issues/48
上得到解答，感谢你的回复！

**Comment by z-x-f** [comment]
> > bcm94360cs2直接免驱的，所以你找错地方了呃
> 
> 你好朋友，这个在15.04上是不免驱的。关于这个问题我已经在：
> [tylernguyen/x1c6-hackintosh#48](https://github.com/tylernguyen/x1c6-hackintosh/issues/48)
> 上得到解答，感谢你的回复！

zhtengw用的是bcm94360cs2，这张卡通过转接卡装x1c上的，直接免驱。你问的是dw1560，是bcm94352z，不是一个东西，所以我说你问错地方了...
