### ISSUE TITLE
请问CFG Lock可以修改吗？

### ISSUE THREAD

**Issue by z-x-f** [zhtengw/EFI-for-X1C6-hackintosh#9]
我的一直是 CFG Lock............................. : 1 (MSR locked until next reset)
用了网上的教程找到bios中cfglock的位置，但是无法修改成功
请问你的有修改过吗？实际使用过程中，cfg lock有什么影响呢？

**Comment by zhtengw** [comment]
我没有关注过CFG Lock的问题，用Hackintool检测了一下，跟你一样是锁定的状态。解锁CFG Lock据说是为了加载AppleIntelCPUPowerManagement.kext，但我这里睡眠正常，就没有特意去关注这个内核扩展了。如果真的在意，给你两个参考链接吧：
1. [Fixing CFG Lock](https://dortania.github.io/OpenCore-Desktop-Guide/extras/msr-lock.html)
2. [Dell Precision 5510 解锁BIOS高级设置](https://hyejeong.cn/unlockbios)

**Comment by zhtengw** [comment]
对了，我这个CPU的原生电源管理是通过加载SSDT-PLUG.aml这个热补丁启用X86PlatformPlugin.kext来实现的，CFG Lock解不解锁应该没影响。
[这里](https://www.tonymacx86.com/threads/guide-native-power-management-for-laptops.175801/)有启用原生电源管理的教程。

**Comment by z-x-f** [comment]
嗯，现在睡眠没问题。那就不管了。
谢谢了哈
